FROM alpine:3.10

ENV http_proxy=http://10.72.28.4:31080\
    https_proxy=http://10.72.28.4:31080

RUN apk add --update nginx && rm -rf /var/cache/apk/*

ADD nginx.conf /etc/nginx/nginx.conf

RUN mkdir /www-data

EXPOSE 80

CMD ["nginx"]
